{% include "header.j2" %}

.PHONY: format
format:
	ruff format

.PHONY: lint
lint:
	yamllint -s -d '{extends: relaxed, rules: {line-length: disable}}' .github/workflows
	bump-my-version bump --dry-run release
	ruff format --check --diff
	ruff check
	{%- if check_manifest %}
	check-manifest
	{%- endif %}
	{%- if lint_requirements %}
	python .ci/scripts/check_requirements.py
	{%- endif %}
	{%- if check_stray_pulpcore_imports %}
	sh .ci/scripts/check_pulpcore_imports.sh
	{%- endif %}
	{%- if check_gettext %}
	sh .ci/scripts/check_gettext.sh
	{%- endif %}
