---
name: "Build"
on:
  workflow_call:

defaults:
  run:
    working-directory: "pulp_catdog"

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v4"
        with:
          path: "plugin_template"
          # We need the full history for bootstrapping
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: "Bootstrap catdog plugin"
        working-directory: "plugin_template"
        run: |
          .ci/bootstrap_catdog.sh

      # Below this line we include the steps of the ci workflow of the generated plugin

      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 1
          repository: "pulp/pulp-openapi-generator"
          path: "pulp-openapi-generator"
      - uses: "actions/setup-python@v5"
      - name: "Install python dependencies"
        run: |
          echo ::group::PYDEPS
          pip install packaging twine wheel mkdocs
          echo ::endgroup::
      - name: "Build package"
        run: |
          python3 setup.py sdist bdist_wheel --python-tag py3
          twine check dist/*
      - name: "Install built packages"
        run: |
          pip install dist/pulp_catdog-*-py3-none-any.whl
      - name: "Generate api specs"
        run: |
          pulpcore-manager openapi --file "api.json"
          pulpcore-manager openapi --bindings --component "catdog" --file "catdog-api.json"
      - name: "Upload Package whl"
        uses: "actions/upload-artifact@v4"
        with:
          name: "plugin_package"
          path: "pulp_catdog/dist/"
          if-no-files-found: "error"
          retention-days: 5
          overwrite: true
      - name: "Upload API specs"
        uses: "actions/upload-artifact@v4"
        with:
          name: "api_spec"
          path: |
            pulp_catdog/api.json
            pulp_catdog/catdog-api.json
          if-no-files-found: "error"
          retention-days: 5
          overwrite: true
      - name: "Build Python bindings packages"
        run: |
          .github/workflows/scripts/build_python_client.sh
        shell: "bash"
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GITHUB_CONTEXT: "${{ github.event.pull_request.commits_url }}"
      - name: "Upload python client packages"
        uses: "actions/upload-artifact@v4"
        with:
          name: "python-client.tar"
          path: |
            pulp_catdog/catdog-python-client.tar
          if-no-files-found: "error"
          retention-days: 5
          overwrite: true
      - name: "Upload python client docs"
        uses: "actions/upload-artifact@v4"
        with:
          name: "python-client-docs.tar"
          path: |
            pulp_catdog/catdog-python-client-docs.tar
          if-no-files-found: "error"
          retention-days: 5
          overwrite: true
      - name: "Build Ruby bindings packages"
        run: |
          .github/workflows/scripts/build_ruby_client.sh
        shell: "bash"
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GITHUB_CONTEXT: "${{ github.event.pull_request.commits_url }}"
      - name: "Upload Ruby client"
        uses: "actions/upload-artifact@v4"
        with:
          name: "ruby-client.tar"
          path: |
            pulp_catdog/catdog-ruby-client.tar
          if-no-files-found: "error"
          retention-days: 5
          overwrite: true
...
